config/routes.rb
Rails.application.routes.draw do
  resources :composes
  resources :entries
  get 'grayscales/index'

  devise_for :users
    
  resources :dashboard

  resources :composes
    
  root to: "home#index"
    
  
    

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_filter :authenticate_user!
    
      before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
   @entries = current_user.entries

  end
 # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = current_user.entries.new(entry_params)
    respond_to do |format|
      if @entry.save
        format.html { redirect_to dashboard_index_path, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_index_path, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:name, :email)
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="login-page">
  <div class="form">
    <form class="login-form">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
          <div class="actions">
    <%= f.submit %>
  </div>
      </form>
  </div>
</div>

<% end %>

app/views/dashboard/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', dashboard_index_path %>

app/views/dashboard/index.html.erb
<p id="notice"><%= notice %></p>

<h1 align="center">Dashboard - Subscribers</h1> 
<br>
<p align="center">To add a new subscriber, click the "+" button</p>
<br>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>Table Style</title>
	<meta name="viewport" content="initial-scale=1.0; maximum-scale=1.0; width=device-width;">
</head>

<body>
<table class="table-fill">
<thead>
    <tr>
      <th>Name&nbsp;&nbsp;</th>
      <th>Email</th>
      <th><div align="center"><button><%= link_to '+', new_dashboard_path %></button></div></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="table-hover">
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.name %></td>
        <td><%= entry.email %>&nbsp;&nbsp;</td>
        <td><%= link_to ' Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>
  

  </body>
    

<br>
    
<div align="center"><button><%= link_to 'Export to CSV', "/entries.csv" %></button></div> <br>

<div align="center"><button><%= link_to 'Email Subscribers', new_compose_path %></button></div>

app/views/dashboard/new.html.erb
<h1 align="center">New Entry</h1>
<div align="center">
<%= render 'form' %>
</div>

app/views/dashboard/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @entry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entry.email %>
</p>

<%= link_to 'Edit', edit_dashboard_path(@entry) %> |
<%= link_to 'Back', dashboard_index_path %>