config/routes.rb
Rails.application.routes.draw do
  resources :composes
  resources :entries
  get 'grayscales/index'

  devise_for :users
    
  resources :dashboard

  resources :composes
    
  root to: "home#index"
    
  
    

end

app/controllers/composes_controller.rb
class ComposesController < ApplicationController
  before_filter :authenticate_user!
    
  before_action :set_compose, only: [:show, :edit, :update, :destroy]

  # GET /composes
  # GET /composes.json
  def index
    @composes = Compose.all
  end

  # GET /composes/1
  # GET /composes/1.json
  def show
  end

  # GET /composes/new
  def new
    @compose = Compose.new
  end

  # GET /composes/1/edit
  def edit
  end

  # POST /composes
  # POST /composes.json
  def create
    @entries = current_user.entries

    @compose = Compose.new(compose_params)

    respond_to do |format|
      if @compose.save
        format.html { redirect_to dashboard_index_path, notice: 'Email(s) were sent successfully.' }
        format.json { render :show, status: :created, location: @compose }
      else
        format.html { render :new }
        format.json { render json: @compose.errors, status: :unprocessable_entity }
      end
    end
      
          @entries.each do |entry| 
            UserMailer.message_user(entry, @compose).deliver
              
          end
      end


  # PATCH/PUT /composes/1
  # PATCH/PUT /composes/1.json
  def update
    respond_to do |format|
      if @compose.update(compose_params)
        format.html { redirect_to @compose, notice: 'Compose was successfully updated.' }
        format.json { render :show, status: :ok, location: @compose }
      else
        format.html { render :edit }
        format.json { render json: @compose.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /composes/1
  # DELETE /composes/1.json
  def destroy
    @compose.destroy
    respond_to do |format|
      format.html { redirect_to composes_url, notice: 'Compose was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compose
      @compose = Compose.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compose_params
      params.require(:compose).permit(:name, :email, :subject, :message)
    end
    
    def entry_params
      params.require(:entry).permit(:name, :email)
    end
end

app/helpers/composes_helper.rb
module ComposesHelper
end

app/views/composes/_form.html.erb
<%= form_for(@compose) do |f| %>
  <% if @compose.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@compose.errors.count, "error") %> prohibited this compose from being saved:</h2>

      <ul>
      <% @compose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="login-page">
  <div class="form">
    <form class="login-form">
    <%= f.label "From" %><br>
    <%= f.text_field :name %>
    <%= f.label "reply to email" %><br>
    <%= f.text_field :email %>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>

    <%= f.label :message %><br>
    <%= f.text_area :message %>
        
<br>
<div class="actions">
    <%= f.submit "Send" %>
        </div>
      </form>
    </div>
</div>
<% end %>

app/views/composes/edit.html.erb
<h1>Editing Compose</h1>

<%= render 'form' %>

<%= link_to 'Show', @compose %> |
<%= link_to 'Back', composes_path %>

app/views/composes/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Listing Composes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Subject</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>


#   <% @composes.each do |compose| %>
      <tr>
        <td><%= compose.name %></td>
        <td><%= compose.email %></td>
        <td><%= compose.subject %></td>
        <td><%= compose.message %></td>
        <td><%= link_to 'Show', compose %></td>
        <td><%= link_to 'Edit', edit_compose_path(compose) %></td>
        <td><%= link_to 'Destroy', compose, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
#    <% end %>
  </tbody>
</table>

<br>

#<%= link_to 'New Compose', new_compose_path %> 
-->

app/views/composes/new.html.erb
<h1 align="center">Compose Mail</h1>
<div align="center">
<%= render 'form' %>
<%= link_to 'Back', dashboard_index_path %>
</div>

app/views/composes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @compose.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @compose.email %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @compose.subject %>
</p>

<p>
  <strong>Message:</strong>
  <%= @compose.message %>
</p>

<%= link_to 'Edit', edit_compose_path(@compose) %> |
<%= link_to 'Back', composes_path %>